# Generated by Django 4.0.6 on 2022-07-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_username_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
