# Generated by Django 4.0.6 on 2022-08-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
